# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm (only dependencies, not devDependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "eslint*"
          - "@eslint*"
          - "typescript*"
          - "@typescript*"
          - "vitest*"
          - "@vitest/*"
          - "@cloudflare/*"
          - "wrangler"
      eslint-typescript-dependencies:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "typescript*"
          - "@typescript*"
      vitest-dependencies:
        patterns:
          - "vitest*"
          - "@vitest/*"
        # Prevent major version upgrades
        ignore:
          - dependency-name: "vitest"
            update-types: ["version-update:semver-major"]
          - dependency-name: "@vitest/*"
            update-types: ["version-update:semver-major"]
      cloudflare-dependencies:
        patterns:
          - "@cloudflare/*"
          - "wrangler"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
